### ISSUE TITLE
Unable to run the plugin

### ISSUE THREAD

**Issue by sergeyzwezdin** [tea3/hexo-auto-link-checker#1]
Steps to reproduce:

1. Install the latest Hexo
2. Install the latest `hexo-auto-link-checker`
3. Run Hexo
```
$ hexo clean
$ hexo s
```
4. There is an error:
```
INFO  Start processing
[hexo-auto-link-checker] Please set the option.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: res.plists.sort is not a function
    at getNextList (/Users/<...removed...>/node_modules/hexo-auto-link-checker/lib/getNextList.js:3:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo

## Environment Info

OS version

```
macOS Catalina 10.15.3
```

Node version(`node -v`)
```
v12.14.0
```
Hexo

```
4.2.0
```

hexo-auto-link-checker

```
1.0.2
```

**Comment by sergeyzwezdin** [comment]
Anyway, I've implemented [my own plugin](https://github.com/sergeyzwezdin/hexo-broken-links-checker) since this doesn't work.

**Comment by forliuyifei** [comment]
> Anyway, I've implemented [my own plugin](https://github.com/sergeyzwezdin/hexo-broken-links-checker) since this doesn't work.

So good!
